---
version: '3'
services:
  postgres:
    image: "postgres:11"
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student
      - POSTGRES_DB=studentdb
    ports: #map ports (host:container)
      - "127.0.0.1:5432:5432"
    volumes: #mount volumes (host:container)
      - udacity_pgdata:/var/lib/postgresql/data
  redis:
    image: redis:3.2.9
    ports: #make redis accessible locally
      - "127.0.0.1:6379:6379"
volumes:
  udacity_pgdata:
