---
version: '3'
services:
  postgres:
    image: "postgres:11"
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student
      - POSTGRES_DB=studentdb
    ports: #map ports (host:container)
      - "127.0.0.1:5432:5432"
    volumes: #mount volumes (host:container)
      - udacity_pgdata:/var/lib/postgresql/data
volumes:
  udacity_pgdata:
