---
version: '3'
services:
  postgres:
    image: "postgres:11"
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student
      - POSTGRES_DB=studentdb
    ports:
      - "5432:5432"
    volumes:
      - udacity_pgdata:/var/lib/postgresql/data
volumes:
  udacity_pgdata:
